#!/bin/bash
# Reference by https://github.com/milador/XAC-Virtual-Joystick

function create_dev(){
  ID=$1
  PROTO=$2
  SUBCLASS=$3
  REPORT_LENG=$4
  DESC=$5
  mkdir -p functions/hid.usb${ID}
  echo $PROTO > functions/hid.usb${ID}/protocol
  echo $SUBCLASS > functions/hid.usb${ID}/subclass
  echo $REPORT_LENG > functions/hid.usb${ID}/report_length
  echo $DESC | xxd -r -ps > functions/hid.usb${ID}/report_desc
  ln -s functions/hid.usb${ID} configs/c.1
}

SWITCHPRO=switch_pro

# Create joystick gadget
cd /sys/kernel/config/usb_gadget/
mkdir -p ${SWITCHPRO}
cd ${SWITCHPRO}

# Define USB specification
echo 0x057e > idVendor
echo 0x2009 > idProduct
echo 0x0200 > bcdDevice            # v1.0.0
echo 0x0200 > bcdUSB               # USB2
echo 0x00 > bDeviceClass           # USB_CSCP_NoDeviceClass 0x00
echo 0x00 > bDeviceSubClass        # USB_CSCP_NoDeviceSubclass 0x00
echo 0x00 > bDeviceProtocol        # USB_CSCP_NoDeviceProtocol 0x00

# Perform localization
mkdir -p strings/0x409

echo "000000000001" > strings/0x409/serialnumber
echo "Nintendo Co., Ltd." > strings/0x409/manufacturer
echo "Pro Controller" > strings/0x409/product

# Create configuration file
mkdir configs/c.1
mkdir configs/c.1/strings/0x409

echo 0x80 > configs/c.1/bmAttributes
echo 500 > configs/c.1/MaxPower # 200 mA
echo "Switch Pro configuration" > configs/c.1/strings/0x409/configuration

# Define the functions of the device
# 0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
# 0x15, 0x00,        // Logical Minimum (0)
# 0x09, 0x04,        // Usage (Joystick)
# 0xA1, 0x01,        // Collection (Application)
# 0x85, 0x30,        //   Report ID (48)
# 0x05, 0x01,        //   Usage Page (Generic Desktop Ctrls)
# 0x05, 0x09,        //   Usage Page (Button)
# 0x19, 0x01,        //   Usage Minimum (0x01)
# 0x29, 0x0A,        //   Usage Maximum (0x0A)
# 0x15, 0x00,        //   Logical Minimum (0)
# 0x25, 0x01,        //   Logical Maximum (1)
# 0x75, 0x01,        //   Report Size (1)
# 0x95, 0x0A,        //   Report Count (10)
# 0x55, 0x00,        //   Unit Exponent (0)
# 0x65, 0x00,        //   Unit (None)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x05, 0x09,        //   Usage Page (Button)
# 0x19, 0x0B,        //   Usage Minimum (0x0B)
# 0x29, 0x0E,        //   Usage Maximum (0x0E)
# 0x15, 0x00,        //   Logical Minimum (0)
# 0x25, 0x01,        //   Logical Maximum (1)
# 0x75, 0x01,        //   Report Size (1)
# 0x95, 0x04,        //   Report Count (4)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x75, 0x01,        //   Report Size (1)
# 0x95, 0x02,        //   Report Count (2)
# 0x81, 0x03,        //   Input (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x0B, 0x01, 0x00, 0x01, 0x00,  //   Usage (0x010001)
# 0xA1, 0x00,        //   Collection (Physical)
# 0x0B, 0x30, 0x00, 0x01, 0x00,  //     Usage (0x010030)
# 0x0B, 0x31, 0x00, 0x01, 0x00,  //     Usage (0x010031)
# 0x0B, 0x32, 0x00, 0x01, 0x00,  //     Usage (0x010032)
# 0x0B, 0x35, 0x00, 0x01, 0x00,  //     Usage (0x010035)
# 0x15, 0x00,        //     Logical Minimum (0)
# 0x27, 0xFF, 0xFF, 0x00, 0x00,  //     Logical Maximum (65534)
# 0x75, 0x10,        //     Report Size (16)
# 0x95, 0x04,        //     Report Count (4)
# 0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0xC0,              //   End Collection
# 0x0B, 0x39, 0x00, 0x01, 0x00,  //   Usage (0x010039)
# 0x15, 0x00,        //   Logical Minimum (0)
# 0x25, 0x07,        //   Logical Maximum (7)
# 0x35, 0x00,        //   Physical Minimum (0)
# 0x46, 0x3B, 0x01,  //   Physical Maximum (315)
# 0x65, 0x14,        //   Unit (System: English Rotation, Length: Centimeter)
# 0x75, 0x04,        //   Report Size (4)
# 0x95, 0x01,        //   Report Count (1)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x05, 0x09,        //   Usage Page (Button)
# 0x19, 0x0F,        //   Usage Minimum (0x0F)
# 0x29, 0x12,        //   Usage Maximum (0x12)
# 0x15, 0x00,        //   Logical Minimum (0)
# 0x25, 0x01,        //   Logical Maximum (1)
# 0x75, 0x01,        //   Report Size (1)
# 0x95, 0x04,        //   Report Count (4)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x34,        //   Report Count (52)
# 0x81, 0x03,        //   Input (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x06, 0x00, 0xFF,  //   Usage Page (Vendor Defined 0xFF00)
# 0x85, 0x21,        //   Report ID (33)
# 0x09, 0x01,        //   Usage (0x01)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x81, 0x03,        //   Input (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x85, 0x81,        //   Report ID (-127)
# 0x09, 0x02,        //   Usage (0x02)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x81, 0x03,        //   Input (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x85, 0x01,        //   Report ID (1)
# 0x09, 0x03,        //   Usage (0x03)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x91, 0x83,        //   Output (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Volatile)
# 0x85, 0x10,        //   Report ID (16)
# 0x09, 0x04,        //   Usage (0x04)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x91, 0x83,        //   Output (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Volatile)
# 0x85, 0x80,        //   Report ID (-128)
# 0x09, 0x05,        //   Usage (0x05)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x91, 0x83,        //   Output (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Volatile)
# 0x85, 0x82,        //   Report ID (-126)
# 0x09, 0x06,        //   Usage (0x06)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x3F,        //   Report Count (63)
# 0x91, 0x83,        //   Output (Const,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Volatile)
# 0xC0,              // End Collection
#
# // 203 bytes
#

#create_dev 0 0 0 160 "050115000904a1018530050105091901290a150025017501950a5500650081020509190b290e150025017501950481027501950281030b01000100a1000b300001000b310001000b320001000b35000100150027ffff0000751095048102c00b39000100150025073500463b0165147504950181020509190f2912150025017501950481027508953481030600ff852109017508953f8103858109027508953f8103850109037508953f9183851009047508953f9183858009057508953f9183858209067508953f9183c0"

# Define the functions of the device

# 0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
# 0x09, 0x04,        // Usage (Joystick)
# 0xA1, 0x01,        // Collection (Application)
# 0xA1, 0x02,        //   Collection (Logical)
# 0x75, 0x08,        //     Report Size (8)
# 0x95, 0x05,        //     Report Count (5)
# 0x15, 0x00,        //     Logical Minimum (0)
# 0x26, 0xFF, 0x00,  //     Logical Maximum (255)
# 0x35, 0x00,        //     Physical Minimum (0)
# 0x46, 0xFF, 0x00,  //     Physical Maximum (255)
# 0x09, 0x32,        //     Usage (Z)
# 0x09, 0x35,        //     Usage (Rz)
# 0x09, 0x30,        //     Usage (X)
# 0x09, 0x31,        //     Usage (Y)
# 0x09, 0x00,        //     Usage (Undefined)
# 0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x75, 0x04,        //     Report Size (4)
# 0x95, 0x01,        //     Report Count (1)
# 0x25, 0x07,        //     Logical Maximum (7)
# 0x46, 0x3B, 0x01,  //     Physical Maximum (315)
# 0x65, 0x14,        //     Unit (System: English Rotation, Length: Centimeter)
# 0x09, 0x39,        //     Usage (Hat switch)
# 0x81, 0x42,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,Null State)
# 0x65, 0x00,        //     Unit (None)
# 0x75, 0x01,        //     Report Size (1)
# 0x95, 0x0C,        //     Report Count (12)
# 0x25, 0x01,        //     Logical Maximum (1)
# 0x45, 0x01,        //     Physical Maximum (1)
# 0x05, 0x09,        //     Usage Page (Button)
# 0x19, 0x01,        //     Usage Minimum (0x01)
# 0x29, 0x0C,        //     Usage Maximum (0x0C)
# 0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x06, 0x00, 0xFF,  //     Usage Page (Vendor Defined 0xFF00)
# 0x75, 0x01,        //     Report Size (1)
# 0x95, 0x08,        //     Report Count (8)
# 0x25, 0x01,        //     Logical Maximum (1)
# 0x45, 0x01,        //     Physical Maximum (1)
# 0x09, 0x01,        //     Usage (0x01)
# 0x81, 0x02,        //     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0xC0,              //   End Collection
# 0xA1, 0x02,        //   Collection (Logical)
# 0x75, 0x08,        //     Report Size (8)
# 0x95, 0x08,        //     Report Count (8)
# 0x46, 0xFF, 0x00,  //     Physical Maximum (255)
# 0x26, 0xFF, 0x00,  //     Logical Maximum (255)
# 0x09, 0x02,        //     Usage (0x02)
# 0x91, 0x02,        //     Output (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
# 0x75, 0x08,        //     Report Size (8)
# 0x95, 0x04,        //     Report Count (4)
# 0x09, 0x02,        //     Usage (0x02)
# 0xB1, 0x02,        //     Feature (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
# 0xC0,              //   End Collection
# 0xC0,              // End Collection
#
# // 109 bytes

c#reate_dev 1 0 0 8 "05010904a101a10275089505150026ff00350046ff00093209350930093109008102750495012507463b0165140939814265007501950c2501450105091901290c81020600ff750195082501450109018102c0a1027508950846ff0026ff0009029102750895040902b102c0c0"

# 0x05, 0x01,        // Usage Page (Generic Desktop Ctrls)
# 0x09, 0x04,        // Usage (Joystick)
# 0xA1, 0x01,        // Collection (Application)
# 0x15, 0x00,        //   Logical Minimum (0)
# 0x25, 0x01,        //   Logical Maximum (1)
# 0x35, 0x00,        //   Physical Minimum (0)
# 0x45, 0x01,        //   Physical Maximum (1)
# 0x75, 0x01,        //   Report Size (1)
# 0x95, 0x10,        //   Report Count (16)
# 0x05, 0x09,        //   Usage Page (Button)
# 0x19, 0x01,        //   Usage Minimum (0x01)
# 0x29, 0x10,        //   Usage Maximum (0x10)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x05, 0x01,        //   Usage Page (Generic Desktop Ctrls)
# 0x25, 0x07,        //   Logical Maximum (7)
# 0x46, 0x3B, 0x01,  //   Physical Maximum (315)
# 0x75, 0x04,        //   Report Size (4)
# 0x95, 0x01,        //   Report Count (1)
# 0x65, 0x14,        //   Unit (System: English Rotation, Length: Centimeter)
# 0x09, 0x39,        //   Usage (Hat switch)
# 0x81, 0x42,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,Null State)
# 0x65, 0x00,        //   Unit (None)
# 0x95, 0x01,        //   Report Count (1)
# 0x81, 0x01,        //   Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x26, 0xFF, 0x00,  //   Logical Maximum (255)
# 0x46, 0xFF, 0x00,  //   Physical Maximum (255)
# 0x09, 0x30,        //   Usage (X)
# 0x09, 0x31,        //   Usage (Y)
# 0x09, 0x32,        //   Usage (Z)
# 0x09, 0x35,        //   Usage (Rz)
# 0x75, 0x08,        //   Report Size (8)
# 0x95, 0x04,        //   Report Count (4)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x06, 0x00, 0xFF,  //   Usage Page (Vendor Defined 0xFF00)
# 0x09, 0x20,        //   Usage (0x20)
# 0x95, 0x01,        //   Report Count (1)
# 0x81, 0x02,        //   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
# 0x0A, 0x21, 0x26,  //   Usage (0x2621)
# 0x95, 0x08,        //   Report Count (8)
# 0x91, 0x02,        //   Output (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
# 0xC0,              // End Collection
#
# // 86 bytes
#

create_dev 2 0 0 3 "05010904a101150025013500450175019510050919012910810205012507463b017504950165140939814265009501810126ff0046ff0009300931093209357508950481020600ff0920950181020a212695089102c0"

# Activate device
ls /sys/class/udc > UDC

sleep 1
